sudo: required
services:
  - docker

before_install:
  - docker build -t bbalachandran/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bbalachandran/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  enviornment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-825674650124"
  bucket_path: "docker-react"

  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"